name: Always Show Tick

on:
  push:
    branches:
      - main

jobs:
  show_tick:
    runs-on: ubuntu-latest
    steps:
      - name: Always Succeed
        id: success_step
        run: exit 0
      
      - name: Show Tick
        if: ${{ success() }}
        run: echo "✅"
